# Generated by Django 4.1.1 on 2022-10-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variotions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variotions',
            new_name='variations',
        ),
    ]
